### ISSUE TITLE
Adding ALB as trigger to Lambda

### ISSUE THREAD

**Issue by rsram312** [s0enke/cloudformation-templates#18]
Does the Load balancer - Lambda template cover how to attach a load balancer to the Lambda function. Currently on using that, I do not see load balancer being attached in the Lambda designer. 

Could you please confirm if it is missing or if I am doing anything wrong?

I was currently referring to this:

https://github.com/s0enke/cloudformation-templates/blob/master/templates/lambda-alb-sam-sample.yaml

@s0enke

**Comment by s0enke** [comment]
The assignment is done in the TargetGroup: 
https://github.com/s0enke/cloudformation-templates/blob/master/templates/lambda-alb-sam-sample.yaml#L39-L45
